"""Generate src/adh/wbs/_generated.py from src/adh/wbs/taxonomy/*.yaml files.

Usage:
    python scripts/gen_wbs_classes.py           # write _generated.py
    python scripts/gen_wbs_classes.py --check   # diff and exit non-zero if out of sync
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

TAXONOMY_DIR = Path(__file__).parent.parent / "src" / "adh" / "wbs" / "taxonomy"
OUTPUT_FILE = Path(__file__).parent.parent / "src" / "adh" / "wbs" / "_generated.py"

FILE_HEADER = """\
# DO NOT EDIT - generated by scripts/gen_wbs_classes.py from src/adh/wbs/taxonomy/
# Re-run the generator if taxonomy/*.yaml files change.

from __future__ import annotations

from typing import Optional

from pydantic import Field

from adh.msosa.architecture import Architecture

"""


def load_entries() -> list[dict]:
    """Load all taxonomy YAML files in sorted order and return combined entry list."""
    entries: list[dict] = []
    for yaml_file in sorted(TAXONOMY_DIR.glob("*.yaml")):
        with yaml_file.open(encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        if data:
            entries.extend(data)
    return entries


def generate_source(entries: list[dict]) -> str:
    """Generate Python source code string from taxonomy entries."""
    lines = [FILE_HEADER]
    for entry in entries:
        wbs_no = entry["wbs_no"]
        class_name = entry["class_name"]
        name = entry["name"]
        standard_ref = entry["standard_ref"]

        docstring = f"{name}. {standard_ref}. WBS {wbs_no}."
        # Classes with underscores in names (disambiguation prefixes) need noqa suppression
        noqa = "  # noqa: N801" if "_" in class_name else ""
        lines.append(f"class {class_name}(Architecture):{noqa}")
        lines.append(f'    """{docstring}"""')
        lines.append("")
        lines.append(
            f'    wbs_no: Optional[str] = Field(default="{wbs_no}", '
            f'description="WBS number per MIL-STD-881F.")'
        )
        lines.append("")
        lines.append("")
    # Remove trailing blank line and end with single newline
    source = "\n".join(lines)
    # Ensure file ends with exactly one newline
    source = source.rstrip("\n") + "\n"
    return source


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate or check src/adh/wbs/_generated.py from taxonomy YAML."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check that _generated.py is up to date; exit non-zero if not.",
    )
    args = parser.parse_args()

    entries = load_entries()
    source = generate_source(entries)

    if args.check:
        if not OUTPUT_FILE.exists():
            print(
                f"ERROR: {OUTPUT_FILE} does not exist. "
                "Run: python scripts/gen_wbs_classes.py"
            )
            sys.exit(1)
        current = OUTPUT_FILE.read_text(encoding="utf-8")
        if current != source:
            print("WBS classes are out of sync. Run: python scripts/gen_wbs_classes.py")
            sys.exit(1)
        print("OK: _generated.py is up to date.")
    else:
        OUTPUT_FILE.write_text(source, encoding="utf-8")
        print(f"Written {len(entries)} classes to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
