name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements.txt

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Set up build cache
        uses: actions/cache/restore@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Python dependencies
        run: |
          pip install .[docs]

      - name: Build MkDocs site
        run: |
          mkdocs --version
          mkdocs gh-deploy --force
