name: Build and deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.11"

      - name: Install the project
        run: |
          uv sync --locked --all-extras --group docs

      - name: Build MkDocs site
        run: |
          uv run mkdocs build

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: site

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
